# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BiometricsSecureStorage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CryptoSwift', '~> 1.7.1'
  # Pods for BiometricsSecureStorage

end
